# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Аналитика.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PySide2 import QtWidgets

from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 430)
        MainWindow.setMinimumSize(QSize(660, 430))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{background: #141529;}\n"
"QPushButton{border: none; text-align: left; color: white; font-family: Consolas;}\n"
"QLabel{color: white; font-size: 11px; font-family: Consolas;}\n"
"QComboBox {background: white; border: none;}\n"
"QComboBox QAbstractItemView { background-color: white;}"
"\n"
"QPushButton::hover{background-color: #2D2F5C}\n"
"QPushButton::pressed{background-color: #44478B}\n"
"\n"
"#frame_2, #frame, #frame QPushButton, #frame_2 QLabel{background: #1F2035; padding-left: 3px;}\n"
"#frame QPushButton::hover{background-color: #2D2F5C;}\n"
"#frame QPushButton::pressed{background-color: #44478B;}\n"
"\n"
"#label{border-bottom: 1px solid;}\n"
"/*-------------------------------------------------*/\n"
"\n"
"#label_8{font-size: 12px; font-family: Consolas;}\n"
"QComboBox{font-family: Consolas; font-size: 13px;}\n"
"#frame_3{background-color: #1B294B;}\n"
"#frame_3 QLabel{background-color: #1B294B; font-size: 11px;}\n"
"#label_6{font-size: 13px;}\n"
"#label_2{font-size: 14px;}\n"
"#label_3, label_4, label_5, label_9{font-family: Consolas; font-size: 10px;}\n"
"#widget_2{background: white;}\n"
"\n"
"#frame #pushButton_3{background: #44478B;}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QFrame(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(170, 0))
        self.frame.setMaximumSize(QSize(170, 16777215))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QPushButton(self.frame)
        self.pushButton.setMinimumSize(QSize(0, 43))
        self.pushButton.setMaximumSize(QSize(99999999, 40))
        font = QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(Qt.LeftToRight)
        icon = QIcon()
        icon.addPixmap(QPixmap("UI\\../icon/home.png"), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QSize(28, 28))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QSize(0, 43))
        self.pushButton_2.setMaximumSize(QSize(99999999, 40))
        font = QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setLayoutDirection(Qt.LeftToRight)
        icon1 = QIcon()
        icon1.addPixmap(QPixmap("UI\\../icon/look.png"), QIcon.Normal, QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QSize(34, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QSize(0, 43))
        self.pushButton_3.setMaximumSize(QSize(99999999, 40))
        font = QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setLayoutDirection(Qt.LeftToRight)
        icon2 = QIcon()
        icon2.addPixmap(QPixmap("UI\\../icon/analitic.png"), QIcon.Normal, QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QSize(33, 33))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_5 = QPushButton(self.frame)
        self.pushButton_5.setMinimumSize(QSize(0, 43))
        self.pushButton_5.setMaximumSize(QSize(99999999, 40))
        font = QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setLayoutDirection(Qt.LeftToRight)
        icon3 = QIcon()
        icon3.addPixmap(QPixmap("UI\\../icon/statistic.png"), QIcon.Normal, QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QSize(33, 33))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_2 = QFrame(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QSize(170, 70))
        self.frame_2.setMaximumSize(QSize(170, 70))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QLabel(self.frame_2)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QSize(16777215, 16777215))
        self.label.setScaledContents(False)
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_4 = QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QGridLayout(self.frame_4)
        self.gridLayout_4.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QLabel(self.frame_4)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QSize(125, 150))
        self.label_7.setMaximumSize(QSize(160, 170))
        self.label_7.setText("")
        self.label_7.setPixmap(QPixmap("UI\\../img/Средние расходы за год.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        spacerItem1 = QSpacerItem(3, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)


        self.fig2 = Figure() #Внешние оболочка графика
        self.fig2.patch.set_alpha(0)
        self.canvas2 = FigureCanvas(self.fig2) #Контейнер для вывода в qt
        self.canvas2.setMinimumSize(QSize(160, 160))
        self.canvas2.setMaximumSize(QSize(180, 180))

        self.gridLayout_2.addWidget(self.canvas2, 1, 0, 1, 1) #Добавить виджет



        spacerItem2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 3, 1, 1)
        self.label_6 = QLabel(self.frame_4)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 3)
        self.gridLayout_4.addLayout(self.gridLayout_2, 2, 1, 2, 1)
        spacerItem3 = QSpacerItem(10, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 2, 0, 2, 1)
        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")

        
        self.fig = Figure() #Внешние оболочка графика
        self.fig.patch.set_alpha(0)
        self.canvas = FigureCanvas(self.fig) #Контейнер для вывода в qt
        self.gridLayout_3.addWidget(self.canvas)

        self.frame_3 = QFrame(self.frame_4)
        self.frame_3.setMinimumSize(QSize(0, 60))
        self.frame_3.setMaximumSize(QSize(16777215, 65))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QSpacerItem(5, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.label_3 = QLabel(self.frame_3)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QLabel(self.frame_3)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QLabel(self.frame_3)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_9 = QLabel(self.frame_3)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        spacerItem5 = QSpacerItem(5, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout_3.addWidget(self.frame_3, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 5)
        spacerItem6 = QSpacerItem(142, 100, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 3, 2, 2, 2)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QLayout.SetMinimumSize)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QSpacerItem(9, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)



        icon4 = QIcon()
        icon4.addPixmap(QPixmap("UI\\../icon/menu.png"), QIcon.Normal, QIcon.Off)

        self.label_2 = QLabel(self.frame_4)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QSize(150, 19))
        self.label_2.setMaximumSize(QSize(99999999, 21))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 5)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, 20, 5, 30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QLabel(self.frame_4)
        self.label_8.setMaximumSize(QSize(135, 16777215))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.comboBox = QComboBox(self.frame_4)
        self.comboBox.setMinimumSize(QSize(135, 21))
        self.comboBox.setMaximumSize(QSize(250, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 2, 2, 1, 2)
        self.gridLayout.addWidget(self.frame_4, 0, 1, 2, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setRowStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Учет коммунальных услуг"))
        self.pushButton.setText(_translate("MainWindow", "Домашняя страница"))
        self.pushButton_2.setText(_translate("MainWindow", "Список платежей"))
        self.pushButton_3.setText(_translate("MainWindow", "Аналитика"))
        self.pushButton_5.setText(_translate("MainWindow", "Статистика"))
        self.label.setText(_translate("MainWindow", "<html><head/><body>\n"
"<p style=\"line-height: 1.2\"><span><b>Адрес:</b><br>\n"
"г. Москва ул градостроительная</span></p>\n"
"</body></html>"))
        self.label_6.setText(_translate("MainWindow", "Средние расходы за год:"))
        self.label_3.setText(_translate("MainWindow", "<html><body style=\"line-height: 1.3;\">\n"
"Самый расходный<br>\n"
"месяц:<br>\n"
"<b style=\"color: #CE8632;\">Март</b>\n"
"</body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><body style=\"line-height: 1.3;\">\n"
"Месяц с минимальными<br>\n"
"расходами:<br>\n"
"<b style=\"color: #CE8632;\">Март</b>\n"
"</body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><body style=\"line-height: 1.3;\">\n"
"Средние расходы:<br><br>\n"
"\n"
"<b style=\"color: #CE8632;\">Март</b>\n"
"</body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><body style=\"line-height: 1.3;\">\n"
"Инфляция с<br>\n"
"прошлым годом:<br>\n"
"<b style=\"color: #CE8632;\">+10%</b>\n"
"</body></html>"))
        self.label_2.setText(_translate("MainWindow", "Аналитика за год"))
        self.label_8.setText(_translate("MainWindow", "Показать за год:"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
