# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Выбор адреса для удаления.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 366)
        MainWindow.setMinimumSize(QSize(320, 250))
        MainWindow.setMaximumSize(QSize(750, 475))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{background: #141529;}\n"
"QPushButton{border: none; color: white; font-family: Consolas; font-size: 13px; background-color: #595877;}\n"
"QLabel{color: white; font-size: 12px; font-family: Consolas;}\n"
"QLineEdit{background-color: white; border: none; font-family: Consolas; font-size: 13px; padding-left: 3px;}\n"
"\n"
"QPushButton::hover{background-color: #737199;}\n"
"QPushButton::pressed{background-color: #8B89B9;}\n"
"\n"
"#label_2{color: #CF2B33;}\n"
"#listWidget {color: white; font-family: Consolas; font-size: 14px}"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QSize(145, 26))
        self.pushButton_2.setMaximumSize(QSize(165, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 3, 1, 1)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 4, 1, 1)
        spacerItem1 = QSpacerItem(15, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 1)
        self.label = QLabel(self.centralwidget)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 3)
        self.listWidget = QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 5)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QSize(145, 26))
        self.pushButton.setMaximumSize(QSize(165, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1)
        spacerItem2 = QSpacerItem(20, 20, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 3)
        spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        spacerItem4 = QSpacerItem(20, 10, QSizePolicy.Minimum, QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 4, 0, 1, 5)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Выбор адреса для удаления"))
        self.pushButton_2.setText(_translate("MainWindow", "Отменить"))
        self.label.setText(_translate("MainWindow", "Выбрать адрес для удаления:"))
        self.pushButton.setText(_translate("MainWindow", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
