# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Индетификация.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 430)
        MainWindow.setMinimumSize(QSize(660, 430))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{background: #141529;}\n"
"QPushButton{background-color: #595973; color: white; font-family: Consolas; font-size: 13px; border-radius: 2px;}\n"
"QComboBox{background-color: white; border: none; font-size: 14px; font-family: Consolas; padding-left: 7px;}\n"
"QLabel{color: white; font-size: 15px; font-family: Consolas;}\n"
"\n"
"QPushButton::hover{background-color: #2D2F5C;}\n"
"QPushButton::pressed{background-color: #44478B;}\n"
"\n"
"#label{font-size: 16px;}\n"
"QComboBox::drop-down{image: url(C:/Users/Mike2/OneDrive/Рабочий стол/Отчетность коммунальных платежей/icon/srelka.png); width: 11px; height: 11px; border: none; padding-right: 3px; padding-top: 3px;}\n"
"QComboBox QAbstractItemView {background-color: white; padding-left: 4px;}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QSpacerItem(20, 65, QSizePolicy.Minimum, QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 1)
        spacerItem2 = QSpacerItem(20, 15, QSizePolicy.Minimum, QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QGridLayout(self.frame_2)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QPushButton(self.frame_2)
        self.pushButton_3.setMinimumSize(QSize(70, 25))
        self.pushButton_3.setMaximumSize(QSize(80, 25))
        self.pushButton_3.setIconSize(QSize(35, 35))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 3, 1, 1)
        self.comboBox = QComboBox(self.frame_2)
        self.comboBox.setMinimumSize(QSize(350, 25))
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 2)
        spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 4, 1, 1)
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 2)
        spacerItem4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 3, 0, 1, 1)
        spacerItem5 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 4, 0, 1, 1)
        self.frame = QFrame(self.centralwidget)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(60, 0, 0, 0)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.pushButton = QPushButton(self.frame)
        self.pushButton.setMinimumSize(QSize(115, 26))
        self.pushButton.setMaximumSize(QSize(105, 26))
        self.pushButton.setIconSize(QSize(35, 35))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QSize(115, 26))
        self.pushButton_2.setMaximumSize(QSize(105, 26))
        self.pushButton_2.setIconSize(QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)
        spacerItem7 = QSpacerItem(15, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Идентификация адреса"))
        self.pushButton_3.setText(_translate("MainWindow", "Войти"))
        self.pushButton_3.setShortcut(_translate("MainWindow", "Return"))
        self.label_2.setText(_translate("MainWindow", "Адрес:"))
        self.pushButton.setText(_translate("MainWindow", "Добавить адрес"))
        self.pushButton.setShortcut(_translate("MainWindow", "+"))
        self.pushButton_2.setText(_translate("MainWindow", "Удалить адрес"))
        self.pushButton_2.setShortcut(_translate("MainWindow", "-"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
