# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Оповещения.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 203)
        MainWindow.setMinimumSize(QSize(340, 190))
        MainWindow.setMaximumSize(QSize(400, 218))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{background: #141529;}\n"
"QPushButton{border: none; color: white; font-family: Consolas; font-size: 13px; background-color: #595877;}\n"
"QLabel{color: white; font-size: 12px; font-family: Consolas;}\n"
"QLineEdit{background-color: white; border: none; font-family: Consolas; font-size: 13px; padding-left: 3px;}\n"
"\n"
"QPushButton::hover{background-color: #737199;}\n"
"QPushButton::pressed{background-color: #8B89B9;}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(10, 0, 0, 9)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QSize(40, 120))
        self.label_2.setText("")
        self.label_2.setPixmap(QPixmap("UI\\../icon/exclamation mark.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.frame = QFrame(self.centralwidget)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QPushButton(self.frame)
        self.pushButton.setMinimumSize(QSize(160, 25))
        self.pushButton.setMaximumSize(QSize(180, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 3, Qt.AlignHCenter)
        self.label = QLabel(self.centralwidget)
        self.label.setMinimumSize(QSize(0, 60))
        self.label.setMaximumSize(QSize(16777215, 200))
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 2)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Оповещение"))
        self.pushButton.setText(_translate("MainWindow", "ОК (10)"))
        self.label.setText(_translate("MainWindow", "<html><head/><body>\n"
"<p style=\"line-height: 1.5\"><span>\n"
"Файл с отчетом сохранен в директории:<br>\n"
"C/data/учет коммунальных услуг<br>\n"
"</span></p>\n"
"</body></html>"))
        self.label_3.setText(_translate("MainWindow", "Оповещение:"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
