# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Посмотреть квитанцию.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 430)
        MainWindow.setMinimumSize(QSize(660, 430))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{background: #141529;}\n"
"QPushButton{border: none; text-align: left; color: white; font-family: Consolas;}\n"
"QLabel{color: white; font-size: 11px; font-family: Consolas;}\n"
"\n"
"QPushButton::hover{background-color: #2D2F5C}\n"
"QPushButton::pressed{background-color: #44478B}\n"
"\n"
"#frame_2, #frame, #frame QPushButton, #frame_2 QLabel{background: #1F2035; padding-left: 3px;}\n"
"#frame QPushButton::hover{background-color: #2D2F5C;}\n"
"#frame QPushButton::pressed{background-color: #44478B;}\n"
"\n"
"#label{border-bottom: 1px solid;}\n"
"/*-------------------------------------------------*/\n"
"QLineEdit{background-color: white; border: none; font-family: Consolas; font-size: 13px; padding-left: 3px;}\n"
"#label_2{font-size: 14px;}\n"
"#pushButton_5{font-size: 11px; text-align: center; background-color: #595876;}\n"
"#label_3{font-size: 12px;}\n"
"#tableView {border: 2px solid black; color: white; font-size: 11px;}\n"
"QHeaderView::section {background-color: #444A83; color: white; font-size: 10px;}"
"QHeaderView {background-color: #27D94B; color: white;}"
"QTableView::item{border: 1px solid;}"
"QMenu {background-color: #454776; border 4px solid black; color: white; font-size: 11px; font-family: Consolas;}"
"QMenu::item:selected {background-color: #6569AD;}"
"\n"
"#frame #pushButton_2{background: #44478B;}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QFrame(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QSize(170, 70))
        self.frame_2.setMaximumSize(QSize(170, 70))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QLabel(self.frame_2)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QSize(16777215, 16777215))
        self.label.setScaledContents(False)
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame = QFrame(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(170, 0))
        self.frame.setMaximumSize(QSize(170, 16777215))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QPushButton(self.frame)
        self.pushButton.setMinimumSize(QSize(0, 43))
        self.pushButton.setMaximumSize(QSize(99999999, 40))
        font = QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(Qt.LeftToRight)
        icon = QIcon()
        icon.addPixmap(QPixmap("UI\\../icon/home.png"), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QSize(28, 28))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QSize(0, 43))
        self.pushButton_2.setMaximumSize(QSize(99999999, 40))
        font = QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setLayoutDirection(Qt.LeftToRight)
        icon1 = QIcon()
        icon1.addPixmap(QPixmap("UI\\../icon/look.png"), QIcon.Normal, QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QSize(34, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QSize(0, 43))
        self.pushButton_3.setMaximumSize(QSize(99999999, 40))
        font = QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setLayoutDirection(Qt.LeftToRight)
        icon2 = QIcon()
        icon2.addPixmap(QPixmap("UI\\../icon/analitic.png"), QIcon.Normal, QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QSize(33, 33))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_6 = QPushButton(self.frame)
        self.pushButton_6.setMinimumSize(QSize(0, 43))
        self.pushButton_6.setMaximumSize(QSize(99999999, 40))
        font = QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setLayoutDirection(Qt.LeftToRight)
        icon3 = QIcon()
        icon3.addPixmap(QPixmap("UI\\../icon/statistic.png"), QIcon.Normal, QIcon.Off)
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setIconSize(QSize(33, 33))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_4 = QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")


        icon4 = QIcon()
        icon4.addPixmap(QPixmap("UI\\../icon/menu.png"), QIcon.Normal, QIcon.Off)

        self.label_2 = QLabel(self.frame_4)
        self.label_2.setMinimumSize(QSize(0, 20))
        self.label_2.setMaximumSize(QSize(16777215, 20))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit = QLineEdit(self.frame_4)
        self.lineEdit.setMinimumSize(QSize(210, 18))
        self.lineEdit.setMaximumSize(QSize(250, 25))
        self.lineEdit.setMaxLength(31)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        #self.pushButton_5 = QPushButton(self.frame_4)
        #self.pushButton_5.setMinimumSize(QSize(120, 22))
        #self.pushButton_5.setObjectName("pushButton_5")
        #self.horizontalLayout_2.addWidget(self.pushButton_5)
        spacerItem2 = QSpacerItem(10, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem3 = QSpacerItem(20, 5, QSizePolicy.Minimum, QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.tableView = QTableView(self.frame_4)
        self.tableView.setObjectName("tableView")

        self.verticalLayout_3.addWidget(self.tableView)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.frame_4, 0, 1, 2, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setRowStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Учет коммунальных услуг"))
        self.label.setText(_translate("MainWindow", "<html><head/><body>\n"
"<p style=\"line-height: 1.2\"><span><b>Адрес:</b><br>\n"
"г. Москва ул градостроительная</span></p>\n"
"</body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Домашняя страница"))
        self.pushButton_2.setText(_translate("MainWindow", "Список платежей"))
        self.pushButton_3.setText(_translate("MainWindow", "Аналитика"))
        self.pushButton_6.setText(_translate("MainWindow", "Статистика"))
        self.label_2.setText(_translate("MainWindow", "Посмотреть квитанцию:"))
        self.label_3.setText(_translate("MainWindow", "Поиск:"))
        #self.pushButton_5.setText(_translate("MainWindow", "Выгрузка Excel"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
